namespace: argocd

resources:
- https://github.com/argoproj-labs/argocd-agent/install/kubernetes/agent?ref=release-0.4
- 10-agent-redis-networkpolicy.yml
- 20-application-controller-cluster-admin-role.yml

images:
- name: ghcr.io/argoproj-labs/argocd-agent/argocd-agent
  newName: quay.io/argoprojlabs/argocd-agent
  newTag: v0.4.1

patches:
  - patch: |
      - op: replace
        path: /data/agent.mode
        value: managed
      - op: replace
        path: /data/agent.server.address
        value: argocd-agent-principal-argocd.apps.cluster-pxkrs.dynamic.redhatworkshops.io
      - op: replace
        path: /data/agent.namespace
        value: argocd
      - op: replace
        path: /data/agent.creds
        value: "mtls:CN=([^,]+)"
      - op: replace
        path: /data/agent.redis.address
        value: argocd-redis:6379
    target:
      kind: ConfigMap
      name: argocd-agent-params